name: pasteshelf

services:
  db:
    image: postgres:17
    container_name: pasteshelf-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    image: pasteshelf-app
    container_name: pasteshelf-app
    depends_on:
      - db
    ports:
      - "${PORT}:8080"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data: